### ISSUE TITLE
Front-end/Backend - 1 (Data Page)

### ISSUE THREAD

**Issue by CianHowell** [RPI-ITWS/armadillo-slay#21]
Paginate Data on data page.  Make functional buttons for filtering, sorting, and downloading. To convert the json to csv https://codingbeautydev.com/blog/javascript-convert-json-to-csv/. To convert the json to netCDF https://github.com/samharrison7/json2netcdf.

Additionally, you will have to work with whoever is creating the endpoints for the filtering and sorting.

Note: netCDF is not crucial JSON and CSV are the most important.

**Comment by anitaprabhakar16** [comment]
Done with data page! FIlter and download buttons work. Able to get data for any county..yay
